import type { EvaluateResponse } from "../../types";
import CoverSection from "./CoverSection";
import SnapshotGrid from "./SnapshotGrid";
import SwotSection from "./SwotSection";
import TrendlyneSection from "./TrendlyneSection";
import FlagsSection from "./FlagsSection";
import FinancialsSection from "./FinancialsSection";
import ValuationSection from "./ValuationSection";
import QualityChecks from "./QualityChecks";
import CompatibilitySection from "./CompatibilitySection";
import VerdictSection from "./VerdictSection";
import BenchmarksSection from "./BenchmarksSection";

interface Props {
  result: EvaluateResponse;
  onBack: () => void;
}

export default function ReportPage({ result, onBack }: Props) {
  const { stock, swot, trendlyne, evaluation } = result;

  function handlePdf() {
    // Open the server-side HTML report in a new tab for printing/PDF
    const body = JSON.stringify({
      ticker: stock.ticker,
      entry_context: "first_purchase",
      profile: {
        age: 30, investment_goal: "wealth_creation", investment_horizon: "5-7 years",
        investment_mode: "lump_sum", portfolio_type: "diversified_10plus",
        position_sizing: "5_to_10", risk_tolerance: "medium",
        volatility_preference: "medium", tax_bracket: "30pct",
      },
    });
    const form = document.createElement("form");
    form.method = "POST";
    form.action = "/api/evaluate/html";
    form.target = "_blank";
    const input = document.createElement("input");
    input.type = "hidden";
    input.name = "body";
    input.value = body;
    // Use a hidden form posting raw JSON via fetch + blob instead
    void openPdfReport(stock.ticker);
  }

  async function openPdfReport(ticker: string) {
    // Re-evaluate to get the HTML report — or just window.print the current page
    window.print();
  }

  return (
    <div className="min-h-screen bg-slate-50 print:bg-white">
      {/* Sticky toolbar */}
      <div className="sticky top-0 z-40 bg-white border-b border-slate-200 px-4 py-2.5 flex items-center justify-between print:hidden">
        <div className="font-bold text-blue-600 tracking-widest text-sm">⚡ QUANTSIEVE</div>
        <div className="flex gap-2">
          <button
            onClick={onBack}
            className="px-4 py-1.5 text-sm border border-slate-200 rounded-lg hover:bg-slate-50 transition font-medium"
          >
            ← New Evaluation
          </button>
          <button
            onClick={handlePdf}
            className="px-4 py-1.5 text-sm bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition font-medium"
          >
            ⬇ Print / PDF
          </button>
        </div>
      </div>

      <div className="max-w-5xl mx-auto px-4 py-6 space-y-5">
        <CoverSection stock={stock} evaluation={evaluation} />
        <SnapshotGrid stock={stock} evaluation={evaluation} />
        <SwotSection swot={swot} />
        {trendlyne && <TrendlyneSection trendlyne={trendlyne} />}
        <FlagsSection evaluation={evaluation} />
        <FinancialsSection evaluation={evaluation} />
        <ValuationSection evaluation={evaluation} stock={stock} />
        <QualityChecks evaluation={evaluation} />
        <CompatibilitySection evaluation={evaluation} />
        <VerdictSection evaluation={evaluation} />
        <BenchmarksSection evaluation={evaluation} />

        {/* Data Gaps */}
        {evaluation.data_gaps.length > 0 && (
          <div className="bg-white border border-slate-200 rounded-xl overflow-hidden">
            <div className="px-5 py-3 border-b border-slate-100 flex items-center gap-2">
              <span className="text-xs font-bold uppercase tracking-widest text-slate-400">Data Gaps</span>
              <span className="text-xs bg-red-100 text-red-700 font-bold px-2 py-0.5 rounded">
                {evaluation.data_gaps.filter(g => g.impact === "MATERIAL").length} material
              </span>
            </div>
            <div className="divide-y divide-slate-100">
              {evaluation.data_gaps.map((g, i) => (
                <div key={i} className="flex items-start gap-3 px-5 py-3">
                  <span className={`text-xs font-bold px-2 py-0.5 rounded mt-0.5 ${g.impact === "MATERIAL" ? "bg-red-100 text-red-700" : "bg-slate-100 text-slate-500"}`}>
                    {g.impact}
                  </span>
                  <div>
                    <div className="text-sm font-medium text-slate-800">{g.metric}</div>
                    <div className="text-xs text-slate-500 mt-0.5">{g.explanation}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        <p className="text-center text-xs text-slate-400 py-4 print:block">
          Generated by QuantSieve · Data from Screener.in · AI via Claude (Anthropic) · For informational purposes only
        </p>
      </div>
    </div>
  );
}
